name             "update-all-packages"
maintainer       "afronski"
maintainer_email "afronski@gmail.com"
license          "MIT License"
description      "It should be first step after installation - upgrade all packages"
version          "0.1.0"