name             "customized-actions-after-install"
maintainer       "afronski"
maintainer_email "afronski@gmail.com"
license          "MIT License"
description      "Perform custom configuration actions after installation"
version          "0.1.0"