name             "packages-to-install"
maintainer       "afronski"
maintainer_email "afrnski@gmail.com"
license          "MIT License"
description      "Main recipe for provisioning system"
version          "0.1.0"