name             "packages-to-remove"
maintainer       "afronski"
maintainer_email "afronski@gmail.com"
license          "MIT License"
description      "Remove unnecessary packages from fresh system installation"
version          "0.1.0"