name             "pacman"
maintainer       "Opscode, Inc."
maintainer_email "cookbooks@opscode.com"
license          "Apache 2.0"
description      "Updates package list for pacman and has LWRP for pacman groups"
version          "1.0.2"