name             "restore-pacman-configuration"
maintainer       "afronski"
maintainer_email "afronski@gmail.com"
license          "MIT License"
description      "Restore all pacman configuration (for multilib and ignore packages support)"
version          "0.1.0"